export const FETCH_PROGRESS_BAR = 'home/FETCH_PROGRESS_BAR';
export const PROGRESS_BAR_RESPONSE = 'home/PROGRESS_BAR_RESPONSE';
export const FETCH_CATEGORIES = 'home/FETCH_CATEGORIES';
export const CATEGORIES_RESPONSE= 'home/CATEGORIES_RESPONSE';
export const FETCH_FOOD_IMPACTS = 'home/FETCH_FOOD_IMPACTS';
export const FETCH_FOOD_IMPACTS_RESPONSE = 'home/FETCH_FOOD_IMPACTS_RESPONSE';
export const FETCH_ARTICLES = 'home/FETCH_ARTICLES';
export const ARTICLES_RESPONSE = 'home/ARTICLES_RESPONSE'; 
